# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
        paths:
          - "test-project/**"
        branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Debug backgroundSpec.js
      run: cat  /home/runner/work/test-project/test-project/earth/fileSpec.js

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Change to your preferred Node.js version
    - name: Clear npm cache
      run: npm cache clean --force
    - name: Clear Yarn cache
      run: yarn cache clean

    - name: Install dependencies
      run: npm install

    - name: Run Jasmine tests
      run:  npm install --save-dev jasmine
    
    - name: config jasmine 
      run:  npm install -g jasmine
    
    - name: config project 
      run:  npx jasmine init

    - name: test project 
      run:  npx jasmine  /home/runner/work/test-project/test-project/earth/fileSpec.js
      
